[package]
name = "adns-ccf"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
build = "build.rs"

[lib]
crate-type = ["staticlib", "rlib"]

[features]
default = []
ccf = ["dep:cxx", "dep:cxx-build"]

[dependencies]
adns-telemetry = { path = "../adns-telemetry" }
adns-auth = { path = "../adns-auth" }
adns-storage = { path = "../adns-storage" }
adns-server = { path = "../adns-server" }
adns-wire = { path = "../adns-wire" }
adns-dnssec = { path = "../adns-dnssec" }
adns-transfer = { path = "../adns-transfer" }
serde.workspace = true
serde_json.workspace = true
hex.workspace = true
ring.workspace = true
cxx = { version = "1", optional = true }

[build-dependencies]
cxx-build = { version = "1", optional = true }

[lints]
workspace = true
