[package]
name = "adns-wire"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true

[dependencies]
serde.workspace = true
thiserror.workspace = true

[dev-dependencies]
allocation-counter = "0.8.1"
criterion.workspace = true
serde_json.workspace = true

[[bench]]
name = "codec"
harness = false

[lints]
workspace = true
