//! The only unsafe boundary is the generated cxx declaration in `bridge`.
//! All application logic and the generic adapter are safe Rust; the C++ wrapper
//! borrows exactly one live CCF transaction during synchronous endpoint calls.
#![deny(unsafe_code)]
#[cfg(feature = "ccf")]
#[allow(unsafe_code)]
mod bridge;

use adns_server::{AppError, AppResponse, ServiceConfiguration, ZoneMetadata};
use adns_storage::{Collection, ReadTx, WriteTx, get_json, put_json};
use adns_wire::{Message, WireName};
use serde::{Deserialize, Serialize};
use serde_json::{Value, json};

pub const CCF_VERSION: &str = "7.0.15";
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(deny_unknown_fields)]
pub struct TransferConfiguration {
    pub key_name: String,
    pub endpoint: String,
    pub zones: Vec<String>,
    pub secret_sha256: String,
    /// Permanent governed tombstone. Legacy active configurations omit this.
    #[serde(default)]
    pub revoked: bool,
}

#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(deny_unknown_fields)]
pub struct TransferSecret {
    pub key_name: String,
    pub secret_base64url: String,
    pub zones: Vec<String>,
}

/// Drain governance-approved zone bootstrap requests. Keys are generated by
/// initialize_zone inside this same confidential transaction, never in JS.
pub fn governed_maintenance(tx: &mut impl WriteTx, now: u64) -> adns_server::Result<Vec<String>> {
    if let Some(mut proposed) =
        get_json::<ServiceConfiguration>(tx, Collection::Lifecycle, b"governance/configuration")?
    {
        validate_governed_configuration(&json!(proposed))?;
        if let Some(current) =
            get_json::<ServiceConfiguration>(tx, Collection::Lifecycle, b"configuration")?
        {
            if proposed.epoch <= current.epoch {
                return Err(AppError::Conflict(
                    "governed configuration epoch must advance",
                ));
            }
            // Governance cannot read the app map, and its mirror may precede
            // many app clock advances. Preserve the current trusted watermark
            // inside the same transaction that installs the new epoch.
            proposed.last_time = proposed.last_time.max(current.last_time);
        }
        put_json(
            tx,
            Collection::Lifecycle,
            b"configuration".to_vec(),
            &proposed,
        )?;
        tx.remove(Collection::Lifecycle, b"governance/configuration")?;
    }
    let mut changed = Vec::new();
    for (key, row) in tx.scan_prefix(Collection::Lifecycle, b"governance/zone/")? {
        let metadata: ZoneMetadata =
            serde_json::from_slice(&row.bytes).map_err(adns_storage::StorageError::from)?;
        if tx
            .get(Collection::Zones, metadata.origin.as_slice())?
            .is_none()
        {
            changed.push(metadata.origin.to_string());
            adns_server::initialize_zone(tx, metadata, now)?;
        }
        tx.remove(Collection::Lifecycle, &key)?;
    }
    let mut maintenance = adns_server::maintenance(tx, now)?;
    changed.append(&mut maintenance);
    changed.sort();
    changed.dedup();
    Ok(changed)
}

pub fn provision_transfer_key(
    tx: &mut impl WriteTx,
    body: &[u8],
) -> adns_server::Result<AppResponse> {
    let v = adns_auth::parse_strict_json(body)?;
    let secret: TransferSecret =
        serde_json::from_value(v).map_err(adns_storage::StorageError::from)?;
    let name: WireName = secret.key_name.parse()?;
    adns_auth::validate_name(&secret.key_name, false)?;
    let secret_bytes = adns_auth::decode_base64url(&secret.secret_base64url, 128)?;
    if secret_bytes.len() < 32 || secret.zones.is_empty() || secret.zones.len() > 128 {
        return Err(AppError::Invalid("transfer secret bounds"));
    }
    // Governance approves names and zones, while the secret arrives only over
    // the loopback enclave interface and is written only to the private map.
    let allowed: TransferConfiguration = get_json(
        tx,
        Collection::Lifecycle,
        format!("governance/transfer/{}", secret.key_name).as_bytes(),
    )?
    .ok_or(AppError::NotFound("governed transfer key"))?;
    if secret.zones != allowed.zones || secret.key_name != allowed.key_name {
        return Err(AppError::Invalid("transfer key zone scope"));
    }
    validate_transfer_configuration(&allowed)?;
    require_active_transfer(&allowed)?;
    if adns_auth::sha256_hex(&secret_bytes) != allowed.secret_sha256 {
        return Err(AppError::Invalid(
            "transfer secret does not match governed digest",
        ));
    }
    if let Some(existing) =
        get_json::<TransferSecret>(tx, Collection::TsigSecrets, name.as_slice())?
    {
        if existing.key_name != secret.key_name
            || existing.zones != secret.zones
            || existing.secret_base64url != secret.secret_base64url
        {
            return Err(AppError::Conflict(
                "transfer key already provisioned; govern a new key name to rotate",
            ));
        }
        // Restart acknowledgement only. Never overwrite existing private
        // material, even when the incoming digest is governance-approved.
        return Ok(AppResponse::new(
            json!({"status":"pending","key_name":secret.key_name,"already_provisioned":true}),
        ));
    }
    for zone in &secret.zones {
        adns_auth::validate_name(zone, false)?;
    }
    put_json(
        tx,
        Collection::TsigSecrets,
        name.as_slice().to_vec(),
        &secret,
    )?;
    Ok(AppResponse::new(
        json!({"status":"pending","key_name":secret.key_name}),
    ))
}

/// Produces already authenticated RFC 5936 frames. The CCF adapter withholds
/// these bytes until the read snapshot's transaction is globally committed.
fn transfer_messages(
    tx: &impl ReadTx,
    packet: &[u8],
    now: u64,
    udp: bool,
) -> adns_server::Result<Vec<Vec<u8>>> {
    if packet.len() > 65535 {
        return Err(AppError::Invalid("AXFR packet too large"));
    }
    // Parse only enough public DNS structure to select an allowed TSIG key;
    // verify_request authenticates the original bytes before reading a zone.
    let message = Message::parse(packet)?;
    let tsig = message
        .additionals
        .last()
        .ok_or(AppError::Invalid("missing TSIG"))?;
    let secret: TransferSecret = get_json(tx, Collection::TsigSecrets, tsig.name.as_slice())?
        .ok_or(AppError::Invalid("unknown TSIG key"))?;
    let config: TransferConfiguration = get_json(
        tx,
        Collection::Lifecycle,
        format!("governance/transfer/{}", secret.key_name).as_bytes(),
    )?
    .ok_or(AppError::NotFound("governed transfer key"))?;
    validate_transfer_configuration(&config)?;
    require_active_transfer(&config)?;
    if config.secret_sha256
        != adns_auth::sha256_hex(&adns_auth::decode_base64url(&secret.secret_base64url, 128)?)
    {
        return Err(AppError::Invalid("transfer key governance digest"));
    }
    let key = adns_transfer::TsigKey::new(
        secret.key_name.parse()?,
        adns_auth::decode_base64url(&secret.secret_base64url, 128)?,
    )
    .map_err(|_| AppError::Invalid("invalid transfer key"))?;
    let query = adns_transfer::verify_request(packet, &key, now)
        .map_err(|_| AppError::Invalid("unauthorized AXFR"))?;
    let origin = query
        .message
        .questions
        .first()
        .ok_or(AppError::Invalid("AXFR question"))?
        .name;
    if !secret.zones.contains(&origin.to_string()) || !config.zones.contains(&origin.to_string()) {
        return Err(AppError::Invalid("TSIG zone scope"));
    }
    let zone = adns_server::zone_metadata(tx, &origin)?;
    if now >= zone.earliest_signature_expiration {
        return Err(AppError::Invalid("zone signatures expired"));
    }
    let question = &query.message.questions[0];
    if udp && question.qtype != adns_wire::RecordType::Soa {
        return Err(AppError::Invalid(
            "UDP peering supports authenticated SOA only",
        ));
    }
    if question.qtype == adns_wire::RecordType::Soa {
        let soa = zone
            .signed_records
            .iter()
            .find(|r| r.name == origin && r.rtype == adns_wire::RecordType::Soa)
            .ok_or(AppError::Invalid("zone SOA missing"))?;
        let mut response = Message {
            header: adns_wire::Header {
                id: query.message.header.id,
                flags: 0x8400,
            },
            questions: vec![question.clone()],
            answers: vec![soa.clone()],
            authorities: Vec::new(),
            additionals: Vec::new(),
        };
        let (mut signed, _) = adns_transfer::sign_message(
            &response.to_wire()?,
            &key,
            now,
            Some(&query.request_mac),
            false,
        )
        .map_err(|_| AppError::Invalid("SOA signing"))?;
        if udp && signed.len() > 1232 {
            response.answers.clear();
            response.header.flags |= 0x0200;
            signed = adns_transfer::sign_message(
                &response.to_wire()?,
                &key,
                now,
                Some(&query.request_mac),
                false,
            )
            .map_err(|_| AppError::Invalid("truncated SOA signing"))?
            .0;
        }
        return Ok(vec![signed]);
    }
    adns_transfer::axfr_messages(&query, &origin, &zone.signed_records, &key, now, 16384)
        .map_err(|_| AppError::Invalid("AXFR serialization"))
}

pub fn transfer(tx: &impl ReadTx, packet: &[u8], now: u64) -> adns_server::Result<Vec<u8>> {
    let mut stream = Vec::new();
    for message in transfer_messages(tx, packet, now, false)? {
        let length =
            u16::try_from(message.len()).map_err(|_| AppError::Invalid("AXFR frame length"))?;
        if stream.len().saturating_add(message.len()).saturating_add(2) > 64 * 1024 * 1024 {
            return Err(AppError::Invalid("transfer exceeds 64 MiB response bound"));
        }
        stream.extend_from_slice(&length.to_be_bytes());
        stream.extend_from_slice(&message);
    }
    Ok(stream)
}

pub fn transfer_datagram(
    tx: &impl ReadTx,
    packet: &[u8],
    now: u64,
) -> adns_server::Result<Vec<u8>> {
    transfer_messages(tx, packet, now, true)?
        .into_iter()
        .next()
        .ok_or(AppError::Invalid("SOA response"))
}

/// Public governance configuration and grant schemas are validated again by
/// Rust on use. Governance never writes encrypted signing key maps directly.
pub fn validate_governed_configuration(value: &Value) -> adns_server::Result<()> {
    let config: ServiceConfiguration =
        serde_json::from_value(value.clone()).map_err(adns_storage::StorageError::from)?;
    if config.audience.is_empty()
        || config.epoch == 0
        || config.last_time > adns_auth::MAX_SAFE_INTEGER
    {
        return Err(AppError::Invalid("service configuration"));
    }
    Ok(())
}

pub fn query_pairs(query: &str) -> adns_server::Result<Vec<(String, String)>> {
    if query.len() > 4096 {
        return Err(AppError::Invalid("query length"));
    }
    fn decode(s: &str) -> adns_server::Result<String> {
        let mut bytes = Vec::new();
        let mut i = 0;
        while i < s.len() {
            match s.as_bytes()[i] {
                b'%' => {
                    let pair = s
                        .get(i + 1..i + 3)
                        .ok_or(AppError::Invalid("query escape"))?;
                    let b = u8::from_str_radix(pair, 16)
                        .map_err(|_| AppError::Invalid("query escape"))?;
                    bytes.push(b);
                    i += 3;
                }
                b'+' => {
                    bytes.push(b' ');
                    i += 1;
                }
                b => {
                    bytes.push(b);
                    i += 1;
                }
            }
        }
        String::from_utf8(bytes).map_err(|_| AppError::Invalid("query UTF-8"))
    }
    let mut out = Vec::new();
    if !query.is_empty() {
        for pair in query.split('&') {
            let (k, v) = pair
                .split_once('=')
                .ok_or(AppError::Invalid("query pair"))?;
            let k = decode(k)?;
            let v = decode(v)?;
            if k.is_empty() || out.iter().any(|(existing, _)| existing == &k) {
                return Err(AppError::Invalid("duplicate query parameter"));
            }
            out.push((k, v));
        }
    }
    Ok(out)
}

pub fn ksk_receipt_claims(
    tx: &mut impl WriteTx,
    query: &str,
    now: u64,
) -> adns_server::Result<AppResponse> {
    let pairs = query_pairs(query)?;
    if pairs.len() != 1 || pairs[0].0 != "zone" {
        return Err(AppError::Invalid("zone query"));
    }
    adns_auth::validate_name(&pairs[0].1, false)?;
    let owner: WireName = pairs[0].1.parse()?;
    let zone = adns_server::zone_metadata(tx, &owner)?;
    let rdata = &zone.ksk_dnskey_rdata;
    if rdata.len() < 5 || rdata[2] != 3 || rdata[3] != 14 {
        return Err(AppError::Invalid("KSK DNSKEY RDATA"));
    }
    let mut ds_data = owner.as_slice().to_vec();
    ds_data.extend_from_slice(rdata);
    let mut ac = 0u32;
    for (i, b) in rdata.iter().enumerate() {
        ac += if i & 1 == 0 {
            u32::from(*b) << 8
        } else {
            u32::from(*b)
        };
    }
    ac += (ac >> 16) & 0xffff;
    let key_tag = ac as u16;
    let claims = adns_server::ksk_claims_digest(&owner, rdata);
    // Force an actual ledger leaf for each requested receipt, including requests
    // for an unchanged KSK. The bounded counter is updated atomically.
    let counter: u64 = get_json(tx, Collection::Lifecycle, b"ksk-receipt-counter")?.unwrap_or(0);
    let counter = counter
        .checked_add(1)
        .ok_or(AppError::Invalid("receipt counter exhausted"))?;
    put_json(
        tx,
        Collection::Lifecycle,
        b"ksk-receipt-counter".to_vec(),
        &counter,
    )?;
    put_json(
        tx,
        Collection::Lifecycle,
        b"ksk-receipt-latest".to_vec(),
        &json!({"owner":owner.to_string(),"claims_digest":hex::encode(claims),"requested_at":now,"counter":counter}),
    )?;
    let mut response = AppResponse::new(
        json!({"zone":owner.to_string(),"owner_name":owner.to_string(),"dnskey_rdata_hex":hex::encode(rdata),"key_tag":key_tag,"algorithm":14,"ds_digest":{"digest_type":2,"digest_hex":adns_auth::sha256_hex(&ds_data)},"status":"pending"}),
    );
    response.claims_digest = Some(claims);
    Ok(response)
}

pub fn validate_transfer_configuration(config: &TransferConfiguration) -> adns_server::Result<()> {
    adns_auth::validate_name(&config.key_name, false)?;
    adns_auth::validate_hex_digest(&config.secret_sha256)?;
    let endpoint: std::net::SocketAddr = config.endpoint.parse().map_err(|_| {
        AppError::Invalid("secondary endpoint must be a canonical numeric socket address")
    })?;
    if endpoint.to_string() != config.endpoint
        || endpoint.port() == 0
        || config.zones.is_empty()
        || config.zones.len() > 128
    {
        return Err(AppError::Invalid("secondary scope"));
    }
    let mut zones = std::collections::BTreeSet::new();
    for zone in &config.zones {
        adns_auth::validate_name(zone, false)?;
        if !zones.insert(zone) {
            return Err(AppError::Invalid("duplicate secondary zone"));
        }
    }
    Ok(())
}

fn require_active_transfer(config: &TransferConfiguration) -> adns_server::Result<()> {
    if config.revoked {
        return Err(AppError::Auth(adns_auth::AuthError::GrantDenied(
            "transfer identity revoked".into(),
        )));
    }
    Ok(())
}

#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(deny_unknown_fields)]
struct SecondaryPending {
    id: String,
    endpoint: String,
    key_name: String,
    zone: String,
    kind: String,
    dns_id: u16,
    request_mac_base64url: String,
    issued_at: u64,
    serial: u32,
}

/// Persist work before exposing its signed datagrams. Global commit is enforced
/// by the CCF response wrapper, so a NOTIFY cannot announce tentative state.
pub fn secondary_requests(
    tx: &mut impl WriteTx,
    body: &[u8],
    now: u64,
) -> adns_server::Result<AppResponse> {
    use adns_wire::{Header, Question, RecordClass, RecordType};
    use ring::rand::{SecureRandom, SystemRandom};
    let parsed = adns_auth::parse_strict_json(body)?;
    if parsed != json!({}) {
        return Err(AppError::Invalid(
            "secondary request body must be empty object",
        ));
    }
    // Reap old in-flight checks. Never grow process-local or durable queues
    // without bound when a secondary is offline.
    let pending_rows = tx.scan_prefix(Collection::Lifecycle, b"secondary/pending/")?;
    let mut outstanding = std::collections::BTreeSet::new();
    for (key, row) in pending_rows {
        let p: SecondaryPending =
            serde_json::from_slice(&row.bytes).map_err(adns_storage::StorageError::from)?;
        let config: Option<TransferConfiguration> = get_json(
            tx,
            Collection::Lifecycle,
            format!("governance/transfer/{}", p.key_name).as_bytes(),
        )?;
        let authorized = config.as_ref().is_some_and(|config| {
            !config.revoked
                && config.key_name == p.key_name
                && config.endpoint == p.endpoint
                && config.zones.contains(&p.zone)
        });
        if !authorized || now < p.issued_at || now.saturating_sub(p.issued_at) >= 300 {
            tx.remove(Collection::Lifecycle, &key)?;
        } else {
            outstanding.insert((p.key_name, p.zone, p.kind));
        }
    }
    let mut configurations = Vec::new();
    let governed_rows = tx.scan_prefix(Collection::Lifecycle, b"governance/transfer/")?;
    // Tombstones count toward the same bound; revoking never frees an identity
    // for reuse or permits an unbounded governance history.
    if governed_rows.len() > 512 {
        return Err(AppError::Invalid("maximum 512 governed secondary keys"));
    }
    for (_, row) in governed_rows {
        let config: TransferConfiguration =
            serde_json::from_slice(&row.bytes).map_err(adns_storage::StorageError::from)?;
        validate_transfer_configuration(&config)?;
        if config.revoked {
            continue;
        }
        if tx
            .get(
                Collection::TsigSecrets,
                config.key_name.parse::<WireName>()?.as_slice(),
            )?
            .is_none()
        {
            continue;
        }
        let key = governed_transfer_key(tx, &config)?;
        configurations.push((config, key));
    }
    let mut jobs = Vec::new();
    for (index, (config, _)) in configurations.iter().enumerate() {
        for zone in &config.zones {
            for kind in ["notify", "soa"] {
                let job = (config.key_name.clone(), zone.clone(), kind.to_string());
                if !outstanding.contains(&job) {
                    jobs.push((job, index));
                }
            }
        }
    }
    jobs.sort_by(|a, b| a.0.cmp(&b.0));
    // Rotate at a durable cursor, so fast healthy peers at the beginning cannot
    // starve later peers when a batch spans more than 256 work items.
    let cursor: Option<(String, String, String)> =
        get_json(tx, Collection::Lifecycle, b"secondary/cursor")?;
    if let Some(cursor) = cursor {
        let pivot = jobs.partition_point(|(job, _)| job <= &cursor);
        jobs.rotate_left(pivot);
    }
    let mut work = Vec::new();
    let mut last = None;
    for (job, index) in jobs {
        if work.len() >= 256 {
            break;
        }
        last = Some(job.clone());
        let (_, name, kind) = job;
        let (config, key) = &configurations[index];
        let origin: WireName = name.parse()?;
        let zone = adns_server::zone_metadata(tx, &origin)?;
        let state: adns_transfer::SecondaryState = get_json(
            tx,
            Collection::SecondaryStatus,
            &adns_storage::composite_key(&[origin.as_slice(), config.endpoint.as_bytes()]),
        )?
        .unwrap_or_default();
        if kind == "notify" && state.last_notified_serial == Some(zone.serial) {
            continue;
        }
        let flags = if kind == "notify" { 0x2400 } else { 0 };
        let mut random = [0u8; 18];
        SystemRandom::new()
            .fill(&mut random)
            .map_err(|_| AppError::Invalid("random source"))?;
        let dns_id = u16::from_be_bytes([random[0], random[1]]);
        let id = hex::encode(&random[2..]);
        let message = Message {
            header: Header { id: dns_id, flags },
            questions: vec![Question {
                name: origin,
                qtype: RecordType::Soa,
                qclass: RecordClass::In,
            }],
            answers: Vec::new(),
            authorities: Vec::new(),
            additionals: Vec::new(),
        };
        let (packet, mac) = adns_transfer::sign_message(&message.to_wire()?, key, now, None, false)
            .map_err(|_| AppError::Invalid("secondary query signing"))?;
        let pending = SecondaryPending {
            id: id.clone(),
            endpoint: config.endpoint.clone(),
            key_name: config.key_name.clone(),
            zone: name,
            kind: kind.clone(),
            dns_id,
            request_mac_base64url: adns_auth::encode_base64url(&mac),
            issued_at: now,
            serial: zone.serial,
        };
        let pending_key = format!("secondary/pending/{id}").into_bytes();
        if tx.get(Collection::Lifecycle, &pending_key)?.is_some() {
            return Err(AppError::Conflict("secondary work ID collision"));
        }
        put_json(tx, Collection::Lifecycle, pending_key, &pending)?;
        work.push(json!({"id":id,"endpoint":config.endpoint,"kind":kind,"packet_base64url":adns_auth::encode_base64url(&packet)}));
    }
    if let Some(cursor) = last {
        put_json(
            tx,
            Collection::Lifecycle,
            b"secondary/cursor".to_vec(),
            &cursor,
        )?;
    }

    Ok(AppResponse::new(json!({"status":"pending","work":work})))
}

pub fn secondary_response(
    tx: &mut impl WriteTx,
    body: &[u8],
    now: u64,
) -> adns_server::Result<AppResponse> {
    #[derive(Deserialize)]
    #[serde(deny_unknown_fields)]
    struct Input {
        id: String,
        endpoint: String,
        response_base64url: String,
    }
    let input: Input = serde_json::from_value(adns_auth::parse_strict_json(body)?)
        .map_err(adns_storage::StorageError::from)?;
    if input.id.len() != 32
        || !input
            .id
            .bytes()
            .all(|b| b.is_ascii_digit() || (b'a'..=b'f').contains(&b))
    {
        return Err(AppError::Invalid("secondary work ID"));
    }
    let pending_key = format!("secondary/pending/{}", input.id).into_bytes();
    let pending: SecondaryPending = get_json(tx, Collection::Lifecycle, &pending_key)?
        .ok_or(AppError::NotFound("secondary work"))?;
    if input.endpoint != pending.endpoint
        || now < pending.issued_at
        || now.saturating_sub(pending.issued_at) >= 300
    {
        return Err(AppError::Invalid("secondary response scope or freshness"));
    }
    let config: TransferConfiguration = get_json(
        tx,
        Collection::Lifecycle,
        format!("governance/transfer/{}", pending.key_name).as_bytes(),
    )?
    .ok_or(AppError::NotFound("governed secondary"))?;
    if config.endpoint != pending.endpoint || !config.zones.contains(&pending.zone) {
        return Err(AppError::Invalid("secondary grant changed"));
    }
    let key = governed_transfer_key(tx, &config)?;
    let packet = adns_auth::decode_base64url(&input.response_base64url, 65535)?;
    let mac = adns_auth::decode_base64url(&pending.request_mac_base64url, 32)?;
    let verified = adns_transfer::verify_message(&packet, &key, now, Some(&mac), false)
        .map_err(|_| AppError::Invalid("secondary response TSIG"))?;
    let m = verified.message;
    let origin: WireName = pending.zone.parse()?;
    let expected_flags = if pending.kind == "notify" {
        0xa400
    } else {
        0x8400
    };
    if m.header.id != pending.dns_id
        || m.header.flags & 0xfe0f != expected_flags
        || m.questions.len() != 1
        || m.questions[0].name != origin
        || m.questions[0].qtype != adns_wire::RecordType::Soa
        || m.questions[0].qclass != adns_wire::RecordClass::In
    {
        return Err(AppError::Invalid("secondary response DNS binding"));
    }
    let state_key = adns_storage::composite_key(&[origin.as_slice(), pending.endpoint.as_bytes()]);
    let mut state: adns_transfer::SecondaryState =
        get_json(tx, Collection::SecondaryStatus, &state_key)?.unwrap_or(
            adns_transfer::SecondaryState {
                endpoint: pending.endpoint,
                ..Default::default()
            },
        );
    if pending.kind == "notify" {
        state.notified(pending.serial);
    } else {
        let soa = m
            .answers
            .iter()
            .filter(|r| {
                r.name == origin
                    && r.rtype == adns_wire::RecordType::Soa
                    && r.rclass == adns_wire::RecordClass::In
            })
            .collect::<Vec<_>>();
        if soa.len() != 1 {
            return Err(AppError::Invalid("secondary SOA count"));
        }
        let adns_wire::RData::Soa(soa) = &soa[0].rdata else {
            return Err(AppError::Invalid("secondary SOA"));
        };
        state.observed(soa.serial, now);
    }
    put_json(tx, Collection::SecondaryStatus, state_key, &state)?;
    tx.remove(Collection::Lifecycle, &pending_key)?;
    Ok(AppResponse::new(
        json!({"status":"pending","secondary":state}),
    ))
}

/// A transaction-consistent read. The CCF wrapper delays its wire bytes until
/// consensus commits that snapshot; expired signatures never reach callers.
pub fn doh(
    tx: &impl ReadTx,
    method: &str,
    query: &str,
    body: &[u8],
    now: u64,
) -> adns_server::Result<Vec<u8>> {
    let packet = match method {
        "GET" => {
            let pairs = query_pairs(query)?;
            if pairs.len() != 1 || pairs[0].0 != "dns" {
                return Err(AppError::Invalid("DoH dns query parameter"));
            }
            adns_auth::decode_base64url(&pairs[0].1, 65535)?
        }
        "POST" => {
            if !query.is_empty() || body.len() > 65535 {
                return Err(AppError::Invalid("DoH body or query"));
            }
            body.to_vec()
        }
        _ => return Err(AppError::Invalid("DoH method")),
    };
    let request = Message::parse(&packet)?;
    if request.header.is_response() || request.questions.len() != 1 {
        return Err(AppError::Invalid("DoH question"));
    }
    adns_server::validate_lifecycle_format(tx)?;
    let zones = tx.scan_prefix(Collection::Zones, b"")?;
    if zones.len() > adns_server::MAX_ZONES {
        return Err(AppError::Invalid(
            "hosted zone count exceeds supported bound",
        ));
    }
    let zones = zones
        .into_iter()
        .map(|(_, row)| {
            serde_json::from_slice::<ZoneMetadata>(&row.bytes)
                .map_err(adns_storage::StorageError::from)
        })
        .collect::<Result<Vec<_>, _>>()?;
    let selected = adns_server::select_query_zone(zones, &request.questions[0]);
    let failure = |rcode: u16| {
        Message {
            header: adns_wire::Header {
                id: request.header.id,
                flags: 0x8000 | (request.header.flags & 0x7910) | rcode,
            },
            questions: request.questions.clone(),
            ..Default::default()
        }
        .to_wire()
        .map_err(AppError::from)
    };
    let Some(zone) = selected else {
        return failure(5);
    };
    if now >= zone.earliest_signature_expiration {
        return failure(2);
    }
    let signed = adns_dnssec::SignedZone::from_signed_records(zone.origin, zone.signed_records)
        .map_err(|e| AppError::Dnssec(e.to_string()))?;
    adns_server::answer_query(&signed, &packet).map_err(AppError::from)
}

fn governed_transfer_key(
    tx: &impl ReadTx,
    config: &TransferConfiguration,
) -> adns_server::Result<adns_transfer::TsigKey> {
    validate_transfer_configuration(config)?;
    require_active_transfer(config)?;
    let name: WireName = config.key_name.parse()?;
    let secret: TransferSecret = get_json(tx, Collection::TsigSecrets, name.as_slice())?
        .ok_or(AppError::NotFound("transfer key"))?;
    let bytes = adns_auth::decode_base64url(&secret.secret_base64url, 128)?;
    if secret.key_name != config.key_name
        || adns_auth::sha256_hex(&bytes) != config.secret_sha256
        || config.zones.iter().any(|zone| !secret.zones.contains(zone))
    {
        return Err(AppError::Invalid(
            "current transfer governance does not match provisioned key",
        ));
    }
    adns_transfer::TsigKey::new(name, bytes).map_err(|_| AppError::Invalid("transfer key"))
}
