#!/usr/bin/env python3
"""Exercise all five outbound mail policy records through real signed CCF APIs.

Run against an explicitly selected, already opened validation service. This
governs one ephemeral operator key and mutates the reserved example.test zone.
No private key is written or exported. Do not run during an idle-only window.
"""
import argparse
import base64
import copy
import hashlib
import json
from pathlib import Path
import sys
import time
import uuid

from cryptography.hazmat.primitives import hashes, serialization
from cryptography.hazmat.primitives.asymmetric import ec, rsa, utils

sys.path.insert(0, str(Path(__file__).resolve().parents[2] / "tools"))
from ccf_control import Client, Governance


def canonical(value):
    # Every field generated by this fixture is ASCII and an integer, which is
    # the RFC8785 subset where sorted compact JSON has identical bytes.
    return json.dumps(value, sort_keys=True, separators=(",", ":"), ensure_ascii=False, allow_nan=False).encode()


def b64(value):
    return base64.urlsafe_b64encode(value).rstrip(b"=").decode()


def sign(key, body):
    signature = key.sign(canonical(body), ec.ECDSA(hashes.SHA256()))
    r, s = utils.decode_dss_signature(signature)
    return {**body, "client_signature": b64(r.to_bytes(32, "big") + s.to_bytes(32, "big"))}


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--url", required=True)
    parser.add_argument("--connect-ip")
    parser.add_argument("--service-cert", type=Path, required=True)
    parser.add_argument("--member-key", type=Path, required=True)
    parser.add_argument("--member-cert", type=Path, required=True)
    parser.add_argument("--output", type=Path, required=True)
    args = parser.parse_args()
    args.output.mkdir(parents=True, exist_ok=False, mode=0o700)
    client = Client(args.url, args.connect_ip, args.service_cert)
    gov = Governance(client, args.member_key, args.member_cert)
    key = ec.generate_private_key(ec.SECP256R1())
    spki = key.public_key().public_bytes(serialization.Encoding.DER, serialization.PublicFormat.SubjectPublicKeyInfo)
    dkim = rsa.generate_private_key(public_exponent=65537, key_size=2048).public_key().public_bytes(serialization.Encoding.DER, serialization.PublicFormat.SubjectPublicKeyInfo)
    entries = [
        ("example.test.", "TXT", "v=spf1 -all"),
        ("selector1._domainkey.example.test.", "TXT", "v=DKIM1; k=rsa; p=" + base64.b64encode(dkim).decode()),
        ("_dmarc.example.test.", "TXT", "v=DMARC1; p=reject; rua=mailto:dmarc@example.test"),
        ("_smtp._tls.example.test.", "TXT", "v=TLSRPTv1; rua=mailto:tlsrpt@example.test"),
        ("example.test.", "CAA", '0 issue "letsencrypt.org"'),
    ]
    now = int(time.time())
    grant_id = "mail-policy-" + uuid.uuid4().hex[:16]
    grant = {"grant_id": grant_id, "subject_spki_sha256": hashlib.sha256(spki).hexdigest(),
             "zones": ["example.test."], "mailbox_domains": [], "service_hosts": [], "roles": [],
             "address_cidrs": [], "ports": [], "allowed_operations": ["operator_records"], "acme_names": [],
             "operator_names": sorted({name for name, _, _ in entries}), "operator_record_types": ["TXT", "CAA"],
             "attested_names": [], "attested_record_types": [],
             "max_lease_seconds": 3600, "max_challenge_lifetime_seconds": 3600,
             "valid_from": now - 60, "valid_until": now + 3600, "revoked": False}
    governed = gov.propose([{"name": "adns_set_owner_grant", "args": {"grant": grant}}])
    (args.output / "grant.json").write_text(json.dumps(grant, indent=2) + "\n")
    (args.output / "expected-records.json").write_text(json.dumps(entries, indent=2) + "\n")

    def committed(method, path, body=None):
        response = client.request(method, path, body)
        if response["http_status"] != 200 or response["headers"].get("x-agentdns-commit-status") != "committed":
            raise ValueError(f"expected committed response: {path}, HTTP {response['http_status']}")
        return client.require_committed(response)

    result = None
    for attempt in range(3):
        state = committed("GET", "/app/zone/status?zone=example.test.")["body"]
        action = {"operation": "operator_records", "request_id": uuid.uuid4().hex, "audience": "ccf://agentdns.test",
                  "grant_id": grant_id, "zone": "example.test.", "signer_spki_der": b64(spki),
                  "parameters": {"expected_serial": state["committed_state"]["serial"],
                                 "mutations": [{"action": "replace", "name": name, "type": kind, "ttl": 300,
                                                "rdata_strings": [value]} for name, kind, value in entries]}}
        nonce = committed("POST", "/app/service/nonce", {"action": action})["body"]
        body = {"action": action, "nonce": nonce["nonce"], "nonce_expires_at": nonce["expires_at"], "intent_hash": nonce["intent_hash"]}
        envelope = sign(key, body)
        der = {**body, "client_signature": b64(key.sign(canonical(body), ec.ECDSA(hashes.SHA256())))}
        rejected_der = client.request("POST", "/app/zone/operator/records", der)
        (args.output / f"attempt-{attempt + 1}-der-response.json").write_text(json.dumps(rejected_der, indent=2) + "\n")
        if rejected_der["http_status"] != 403 or not any(code in str(rejected_der["body"]) for code in ("INVALID_FIELD", "INVALID_SIGNATURE")):
            raise ValueError("DER request signature was not rejected")
        started = time.perf_counter_ns()
        response = client.request("POST", "/app/zone/operator/records", envelope)
        elapsed_ms = (time.perf_counter_ns() - started) / 1e6
        response_path = args.output / f"attempt-{attempt + 1}-operator-response.json"
        response_path.write_text(json.dumps(response, indent=2) + "\n")
        if response["http_status"] == 409 and "expected_serial" in str(response["body"]):
            continue  # Autonomous DNSSEC refresh changed the expected serial.
        if response["http_status"] != 200 or response["headers"].get("x-agentdns-commit-status") != "committed":
            raise ValueError(f"operator mutation failed: HTTP {response['http_status']}; response retained in {response_path}")
        result = client.require_committed(response)
        break
    if result is None:
        raise ValueError("zone serial changed during every bounded attempt")
    retry = committed("POST", "/app/zone/operator/records", envelope)
    if retry["body"] != result["body"] or retry["confirmed_ccf_transaction_id"] != result["confirmed_ccf_transaction_id"]:
        raise ValueError("identical retry changed the historical result")
    changed = copy.deepcopy(body)
    changed["action"]["parameters"]["mutations"][0]["rdata_strings"] = ["v=spf1 ~all"]
    changed["intent_hash"] = hashlib.sha256(canonical(changed["action"])).hexdigest()
    conflict = client.request("POST", "/app/zone/operator/records", sign(key, changed))
    if conflict["http_status"] != 409 or "REQUEST_ID_CONFLICT" not in str(conflict["body"]):
        raise ValueError("conflicting signed request ID was not rejected")
    for name, value in [("grant.json", grant), ("expected-records.json", entries),
                        ("signed-request.json", envelope), ("result.json", result),
                        ("retry.json", retry), ("der-rejection.json", rejected_der), ("conflict.json", conflict)]:
        (args.output / name).write_text(json.dumps(value, indent=2) + "\n")
    summary = {"scope": "real governed operator mutation, not attested registration or email delivery",
               "transaction_id": result["confirmed_ccf_transaction_id"], "zone_serial": result["body"]["zone_serial"],
               "governance_transaction_id": governed["confirmed_ccf_transaction_id"],
               "policies": ["SPF", "DKIM", "DMARC", "TLSRPT", "CAA"],
               "dkim_txt_exceeds_255_bytes": len(entries[1][2]) > 255,
               "der_rejected_without_consuming_nonce": True, "exact_retry_preserves_original_result": True,
               "changed_signed_action_returns_conflict": True,
               "operator_commit_latency_ms_including_tls": elapsed_ms}
    (args.output / "summary.json").write_text(json.dumps(summary, indent=2) + "\n")
    print(json.dumps(summary, indent=2))


if __name__ == "__main__":
    main()
